"""Monthly Goals Update

Revision ID: 08b764ca5bb8
Revises: 0b03ba7949a1
Create Date: 2023-11-16 19:42:18.843852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08b764ca5bb8'
down_revision = '0b03ba7949a1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monthlygoal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('goal1', sa.String(), nullable=True),
    sa.Column('goal2', sa.String(), nullable=True),
    sa.Column('goal3', sa.String(), nullable=True),
    sa.Column('goal4', sa.String(), nullable=True),
    sa.Column('goal5', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('monthlygoal')
    # ### end Alembic commands ###
