"""create user and blog table migrations

Revision ID: 251040fd8696
Revises: 
Create Date: 2023-10-12 14:52:22.633983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '251040fd8696'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
