"""empty message

Revision ID: 5f25f2dbd277
Revises: 08b764ca5bb8
Create Date: 2023-11-23 13:09:56.298513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f25f2dbd277'
down_revision = '08b764ca5bb8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
